version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: qlkh_db
      POSTGRES_USER: qlkh_user
      POSTGRES_PASSWORD: qlkh_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
