# Generated by Django 5.2.13 on 2026-04-25 03:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Mã KH')),
                ('name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('group_name', models.CharField(default='Mặc định', max_length=100, verbose_name='Nhóm KH')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], default='Nam', max_length=20, verbose_name='Giới tính')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Điện thoại')),
                ('email', models.EmailField(default='', max_length=255, verbose_name='Email')),
                ('customer_type', models.CharField(choices=[('VIP', 'VIP'), ('Thường', 'Thường')], default='Thường', max_length=50, verbose_name='Loại KH')),
                ('cmnd', models.CharField(blank=True, default='', max_length=30, verbose_name='CMND/CCCD')),
                ('birth_date', models.CharField(blank=True, default='', max_length=30, verbose_name='Ngày sinh')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Địa chỉ')),
                ('product', models.CharField(default='', max_length=255, verbose_name='Sản phẩm')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.BigIntegerField(default=0, verbose_name='Đơn giá')),
                ('total_amount', models.BigIntegerField(default=0, verbose_name='Thành tiền')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
