# Generated by Django 5.2.13 on 2026-04-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cluster_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nhóm phân cụm'),
        ),
        migrations.AddField(
            model_name='customer',
            name='feedback',
            field=models.TextField(blank=True, default='', verbose_name='Phản hồi khách hàng'),
        ),
        migrations.AddField(
            model_name='customer',
            name='satisfaction_label',
            field=models.CharField(blank=True, choices=[('satisfied', 'Hài lòng'), ('neutral', 'Trung lập'), ('dissatisfied', 'Không hài lòng'), ('', 'Chưa đánh giá')], default='', max_length=20, verbose_name='Mức độ hài lòng'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sentiment_label',
            field=models.CharField(blank=True, choices=[('positive', '😊 Tích cực'), ('neutral', '😐 Trung lập'), ('negative', '😞 Tiêu cực'), ('', 'Chưa phân tích')], default='', max_length=20, verbose_name='Nhãn cảm xúc'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm cảm xúc'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type', 'sentiment_label'], name='customers_c_custome_2b8319_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['satisfaction_label'], name='customers_c_satisfa_c0858d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['cluster_id'], name='customers_c_cluster_42c67a_idx'),
        ),
    ]
